---
development:
  cloud_name: quytv020494
  api_key: '839297578577554'
  api_secret: 8zMg774PtNbSqE3Js6ygGXOx4I8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: quytv020494
  api_key: '839297578577554'
  api_secret: 8zMg774PtNbSqE3Js6ygGXOx4I8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: quytv020494
  api_key: '839297578577554'
  api_secret: 8zMg774PtNbSqE3Js6ygGXOx4I8
  enhance_image_tag: true
  static_image_support: false
